### PR TITLE
task/DES-3002 create test datasets from OpenTopography

### PR DESCRIPTION
**Pull request by Beulah-Karrolla**
## PR Status: ##

* [X] Ready.
* [ ] Work in Progress.
* [ ] Hold.

## Related Jira tickets: ##

* [DES-3002](https://tacc-main.atlassian.net/browse/DES-3002)

## Summary of Changes: ##

- Added 10 random datasets from OpenTopology in the finalized json format along with features extracted from their spatial data catalog. 
- This data can be used in the initial run for methodology working and later for any unit tests.

### CODE REVIEW

**Review by fnets — CHANGES_REQUESTED** [review]
These files will be placed in Community Data on DesignSafe, not in the actual codebase. Do you think you could email them to me?

**Comment by Beulah-Karrolla** [comment]
The updated test geojson files, along with dataset description can be found attached on the JIRA ticket [DES-3002](https://tacc-main.atlassian.net/browse/DES-3002).

**Comment by nathanfranklin** [comment]
> These files will be placed in Community Data on DesignSafe, not in the actual codebase

I think they can be used as test fixtures in the backend or on the client side.  So maybe their exact location might change (🤔 ) but we can add them.

**Review by nathanfranklin — COMMENTED** [review]
LGTM 👍

**Review by nathanfranklin — APPROVED** [review]
LGTM 👍

**Review by fnets — APPROVED** [review]
LGTM!

**Pull request merged**
