### PR TITLE
Task/des-1350 - Changes to Workspace file listings

### PR DESCRIPTION
**Pull request by fnets**
The Data Browser in the Workspace now loads publications in the same order as they are displayed in the Data Depot.

### CODE REVIEW

**Comment by fnets** [comment]
@Strmiska good catch, thanks!

**Comment by fnets** [comment]
@Strmiska done

**Comment by fnets** [comment]
@jarosenb squashed!

**Comment by jarosenb** [comment]
Merged into Python 3 branch, will close when that branch moves to prod.

**Comment by fnets** [comment]
@rstijerina done!  Thanks to @jarosenb

**Pull request merged**
